### PR TITLE
Updated using PocketAI's new Lint Hunting and Optimizations

### PR DESCRIPTION
**Pull request by NopeNotDark**
TIP: don't give PocketAI access to your github token (it ends up deleting the repo you give it)

### CODE REVIEW

**Comment by SantanasWrld** [comment]
were you using PocketAI build 1.10-PRE or were you using the stable build 1.01.2?

**Comment by SantanasWrld** [comment]
i have no interest in using dev builds on production plugins

**Comment by NopeNotDark** [comment]
> were you using PocketAI build 1.10-PRE or were you using the stable build 1.01.2?
> 
> 

On Stable 1.01.1

**Comment by SantanasWrld** [comment]
pocketai has logs of these messages so i can confirm it was generated

**Pull request merged**
